server:
  port: 9001

mybatis-mini:
  isReadExcludePrimary: false

spring:
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      #jdbc-url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
      jdbc-url: jdbc:h2:mem:db_users;MODE=MYSQL;INIT=RUNSCRIPT FROM './src/test/resources/db-init.sql'
      username: root
      password: 123456
