server:
  port: 9001

mybatis-mini:
  isReadExcludePrimary: false
  isReadAllScopeOpen: false
  logRead: true
  logWrite: true
  logFullSql: true

spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test_b?autoReconnect=true&rewriteBatchedStatements=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=CTT
      username: root
      password: 123456
#